# =================================================================
# HUGO 主配置文件 (hugo.toml)
# =================================================================
baseURL = "https://rycCJ.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Can's Blog"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 0
enableEmoji = true

# 这是一个独立的顶级配置，告诉 Hugo 不要为分类法和词条页面生成独立的页面
# 这也会影响 sitemap 的生成，因为这些页面从一开始就不会被创建
excludedKinds = ["taxonomy", "term"]

# 分页设置
[pagination]
pagerSize = 10

# 图片处理
[imaging]
anchor = 'Center'

# 分类法定义
[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

# 站点地图设置
[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

# 输出格式，确保有 JSON 以支持搜索
[outputs]
home = ["HTML", "RSS", "JSON"]

# 相关文章设置
[related]
threshold = 0
toLower = false
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "categories"
weight = 100

[params]
  customCSS = ["css/custom.css"] # <-- 直接在这里添加
# Firebase 配置 (请填入您的真实密钥)
[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"
