# =================================================================
# BLOWFISH 主题参数文件 (params.toml)
# =================================================================

# --- 常规设置 ---
colorScheme = "ocean"
defaultAppearance = "dark"      # 您可以改为 'light'
autoSwitchAppearance = true
disableImageOptimization = true # 全局禁用图片优化，如果您自己处理图片的话
disableTextInHeader = false
# 版权信息，使用 {year} 占位符
copyright = "© 2024-{year} Can. All rights reserved."

# --- 特色图片 ---
defaultBackgroundImage = "/img/lofi-girl-reading-book-while-its-raining-outside-pixel-moewalls-com-ezgif.com-video-to-gif-converter.gif"
# defaultFeaturedImage = "/img/chill-mario-pixel-moewalls-com-ezgif.com-crop.gif"
defaultSocialImage = "/img/lofi-girl-reading-book-while-its-raining-outside-pixel-moewalls-com-ezgif.com-video-to-gif-converter.gif"

# --- 功能开关 ---
enableSearch = true
enableCodeCopy = true
replyByEmail = true
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

# --- 头部 ---
[header]
layout = "basic"

# --- 页脚 ---
[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

# --- 主页 ---
[homepage]
layout = "background" # 您之前想用的 hero 布局
showRecent = true
showRecentItems = 5

# --- 文章页面 ---
[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showReadingTime = true
showWordCount = true
showTableOfContents = true # 建议在文章页开启目录
showTaxonomies = true      # 在文章末尾显示标签和分类
showPagination = true
showViews = true           # 如果配置了 Firebase，设为 true
showLikes = true           # 如果配置了 Firebase，设为 true

# --- 列表页面 ---
[list]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showSummary = true       # 建议在列表页显示摘要
groupByYear = true

# --- 分类法和词条页面 ---
[taxonomy]
showTermCount = true
showHero = false     # 建议分类页保持简洁

[term]
showHero = false # 建议词条页保持简洁
