# .github/workflows/deploy.yml
# 用于双仓库模式的部署流程
name: Deploy to rycCJ.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

# 授予工作流向您的仓库写入内容的权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_TOKEN }} # <--- 修改这一行
          # 部署到您的 GitHub Pages 发布仓
          external_repository: rycCJ/rycCJ.github.io
          # 推送到目标仓库的 main 分支
          publish_branch: main
          # Hugo生成的网站文件默认在 public 目录
          publish_dir: ./public
          # 提交代码时使用的用户名和邮箱
          user_name: 'rycCJ'
          user_email: 'ryc1819009649@outlook.com'